# Generated by Django 4.1.7 on 2023-04-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_address_order_payment_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=100, null=True)),
                ('discount', models.IntegerField(default=100)),
                ('is_expired', models.BooleanField(default=False)),
                ('minimum_amount', models.IntegerField(default=500)),
            ],
        ),
    ]
