# Generated by Django 4.1.7 on 2023-04-24 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_cartitems_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_amount',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
