# Generated by Django 4.1.7 on 2023-04-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_coupon_is_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('out for delivery', 'out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'cancelled'), ('Returned', 'Returned')], default='Pending', max_length=200),
        ),
    ]
