# Generated by Django 4.1.7 on 2023-05-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=120)),
                ('title2', models.CharField(max_length=120)),
                ('image1', models.ImageField(upload_to='ecom/image')),
                ('tag', models.CharField(max_length=120)),
            ],
        ),
    ]
