# Generated by Django 4.1.7 on 2023-05-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_coupon_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_price',
        ),
    ]
