# Generated by Django 4.1.7 on 2023-05-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.IntegerField(default=40),
        ),
    ]
